version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3305:3306'
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
#      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=valora
#      - MYSQL_USER=ricardo
#      - MYSQL_PASSWORD=belter_2017
      - MYSQL_ROOT_PASSWORD=123456_abc

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db